# Catching Exceptions

Catching exceptions handle the unexpected exception manually by resolving the issue or notifying the developer or application user. When an exception is thrown, it interrupts the normal execution of the program. You can handle exceptions gracefully with the `try` and `catch` keywords to keep your program stable. The `try` block contains the code that might throw an exception, while the `catch` block catches and handles the exception if it occurs. The exception is caught by the first `catch` block that matches its specific type or a superclass of the exception.

Visit the following resources to learn more:

- [@official@Handle exceptions using try-catch blocks](https://kotlinlang.org/docs/exceptions.html#handle-exceptions-using-try-catch-blocks)